---
title: 03 - Graphical Causal Models
jupyter: python3
---

 
 

 
## Thinking About Causality
 


```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:27.723424Z', start_time: '2023-06-25T15:09:25.235237Z'}
#| tags: [hide-input, hide-output]
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import graphviz as gr
from matplotlib import style
import seaborn as sns
from matplotlib import pyplot as plt

color=['0.3', '0.5', '0.7', '0.9']
linestyle=['-', '--', ':', '-.']
marker=['o', 'v', 'd', 'p']

pd.set_option('display.max_rows', 6)

gr.set_default_format("png");
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:27.743557Z', start_time: '2023-06-25T15:09:27.725297Z'}
import pandas as pd
import numpy as np

data = pd.read_csv("./data/cross_sell_email.csv")
data
```


### Visualizing Causal Relationships 

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:28.364202Z', start_time: '2023-06-25T15:09:27.744786Z'}
#| tags: [hide-output]
import graphviz as gr

g_cross_sell = gr.Digraph()

g_cross_sell.edge("U", "conversion")
g_cross_sell.edge("U", "age")
g_cross_sell.edge("U", "gender")

g_cross_sell.edge("rnd", "cross_sell_email")
g_cross_sell.edge("cross_sell_email", "conversion")
g_cross_sell.edge("age", "conversion")
g_cross_sell.edge("gender", "conversion")

g_cross_sell
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:28.575818Z', start_time: '2023-06-25T15:09:28.367014Z'}
#| tags: [hide-input]
g_cross_sell = gr.Digraph()

g_cross_sell.edge("U", "conversion")
g_cross_sell.edge("U", "age")
g_cross_sell.edge("U", "gender")

g_cross_sell.edge("rnd", "cross_sell_email")
g_cross_sell.edge("cross_sell_email", "conversion")
g_cross_sell.edge("age", "conversion")
g_cross_sell.edge("gender", "conversion")

g_cross_sell
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:28.798849Z', start_time: '2023-06-25T15:09:28.578426Z'}
#| tags: [hide-output]
# rankdir:LR layers the graph from left to right
g_cross_sell = gr.Digraph(graph_attr={"rankdir": "LR"})

g_cross_sell.edge("U", "conversion")
g_cross_sell.edge("U", "X")

g_cross_sell.edge("cross_sell_email", "conversion")
g_cross_sell.edge("X", "conversion")

g_cross_sell
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:29.004349Z', start_time: '2023-06-25T15:09:28.801559Z'}
#| tags: [hide-input]
g_cross_sell = gr.Digraph(graph_attr={"rankdir": "LR"})

g_cross_sell.edge("U", "conversion")
g_cross_sell.edge("U", "X")

g_cross_sell.edge("cross_sell_email", "conversion")
g_cross_sell.edge("X", "conversion")

g_cross_sell
```

 
### Are Consultants Worth it?

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:29.204706Z', start_time: '2023-06-25T15:09:29.006360Z'}
#| tags: [hide-input, hide-code]
g_consultancy = gr.Digraph(graph_attr={"rankdir": "LR"})

g_consultancy.edge("U1", "profits_next_6m")
g_consultancy.edge("U2", "consultancy")
g_consultancy.edge("U3", "profits_prev_6m")

g_consultancy.edge("consultancy", "profits_next_6m")

g_consultancy.edge("profits_prev_6m", "consultancy")
g_consultancy.edge("profits_prev_6m", "profits_next_6m")

g_consultancy
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:29.429558Z', start_time: '2023-06-25T15:09:29.207127Z'}
#| tags: [hide-input, hide-code]
g_consultancy = gr.Digraph(graph_attr={"rankdir":"LR"})

g_consultancy.edge("consultancy", "profits_next_6m")
g_consultancy.edge("profits_prev_6m", "consultancy")
g_consultancy.edge("profits_prev_6m", "profits_next_6m")

g_consultancy
```

## Crash Course in Graphical Models
 
 
### Chains

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:29.656253Z', start_time: '2023-06-25T15:09:29.431670Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir": "LR"})

g.edge("T", "M")
g.edge("M", "Y")
g.node("M", "M")


g.edge("causal knowledge", "solve problems")
g.edge("solve problems", "job promotion")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:29.870382Z', start_time: '2023-06-25T15:09:29.661788Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir": "LR"})

g.edge("T", "M")
g.edge("M", "Y")
g.node("M", "M")
g.node("M", color="lightgrey", style="filled")


g.edge("causal knowledge", "solve problems")
g.edge("solve problems", "job promotion")
g.node("solve problems", color="lightgrey", style="filled")

g
```


### Forks
 

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:30.108147Z', start_time: '2023-06-25T15:09:29.872267Z'}
#| tags: [hide-input]
g = gr.Digraph()


g.edge("X", "Y")
g.edge("X", "T")
g.node("X", "X")

g.edge("statistics", "causal inference")
g.edge("statistics", "machine learning")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:30.323535Z', start_time: '2023-06-25T15:09:30.110294Z'}
#| tags: [hide-input]
g = gr.Digraph()

g.edge("good programmer", "can invert a binary tree")
g.edge("good programmer", "good employee")

g
```


 
### Immorality or Collider 

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:30.517990Z', start_time: '2023-06-25T15:09:30.326021Z'}
#| tags: [hide-input]
g = gr.Digraph()

g.edge("Y", "X")
g.edge("T", "X")

g.edge("statistics", "job promotion")
g.edge("flatter", "job promotion")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:30.744680Z', start_time: '2023-06-25T15:09:30.519766Z'}
#| scrolled: true
#| tags: [hide-input]
g = gr.Digraph()

g.edge("Y", "X1")
g.edge("T", "X1")
g.edge("X1", "X2")
g.node("X2", color="lightgrey", style="filled")

g.edge("statistics", "job promotion")
g.edge("flatter", "job promotion")
g.edge("job promotion", "high salary")

g.node("high salary", color="lightgrey", style="filled")

g
```

### The Flow of Association Cheat Sheet

### Querying a Graph in Python

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:30.952339Z', start_time: '2023-06-25T15:09:30.746564Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir": "LR"})
g.edge("C", "A")
g.edge("C", "B")
g.edge("D", "A")
g.edge("B", "E")
g.edge("F", "E")
g.edge("A", "G")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.066650Z', start_time: '2023-06-25T15:09:30.954496Z'}
import networkx as nx

model = nx.DiGraph([
    ("C", "A"),
    ("C", "B"),
    ("D", "A"),
    ("B", "E"),
    ("F", "E"),
    ("A", "G"),
])
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.073162Z', start_time: '2023-06-25T15:09:31.068365Z'}
print("Are D and C dependent?")
print(not(nx.d_separated(model, {"D"}, {"C"}, {})))

print("Are D and C dependent given A?")
print(not(nx.d_separated(model, {"D"}, {"C"}, {"A"})))

print("Are D and C dependent given G?")
print(not(nx.d_separated(model, {"D"}, {"C"}, {"G"})))
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.077511Z', start_time: '2023-06-25T15:09:31.074704Z'}
print("Are G and D dependent?")
print(not(nx.d_separated(model, {"G"}, {"D"}, {})))

print("Are G and D dependent given A?")
print(not(nx.d_separated(model, {"G"}, {"D"}, {"A"})))
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.082324Z', start_time: '2023-06-25T15:09:31.079124Z'}
print("Are A and B dependent?")
print(not(nx.d_separated(model, {"A"}, {"B"}, {})))

print("Are A and B dependent given C?")
print(not(nx.d_separated(model, {"A"}, {"B"}, {"C"})))
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.087167Z', start_time: '2023-06-25T15:09:31.083938Z'}
print("Are G and F dependent?")
print(not(nx.d_separated(model, {"G"}, {"F"}, {})))

print("Are G and F dependent given E?")
print(not(nx.d_separated(model, {"G"}, {"F"}, {"E"})))
```


 
## Identification Revisited

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.290464Z', start_time: '2023-06-25T15:09:31.088696Z'}
#| tags: [hide-input]
consultancy_sev = gr.Digraph(graph_attr={"rankdir": "LR"})
consultancy_sev.edge("profits_prev_6m", "profits_next_6m")
consultancy_sev.edge("profits_prev_6m", "consultancy")

consultancy_sev
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.297704Z', start_time: '2023-06-25T15:09:31.292738Z'}
consultancy_model_severed = nx.DiGraph([
    ("profits_prev_6m", "profits_next_6m"),
    ("profits_prev_6m", "consultancy"),
#     ("consultancy", "profits_next_6m"), # causal relationship removed
])

not(nx.d_separated(consultancy_model_severed,
                   {"consultancy"}, {"profits_next_6m"}, {}))
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.505182Z', start_time: '2023-06-25T15:09:31.299411Z'}
#| tags: [hide-input]
g_consultancy = gr.Digraph(graph_attr={"rankdir":"LR"})
g_consultancy.edge("profits_prev_6m", "profits_next_6m")
g_consultancy.edge("profits_prev_6m", "consultancy")
g_consultancy.edge("consultancy", "profits_next_6m")
g_consultancy.node("profits_prev_6m", color="lightgrey", style="filled")

g_consultancy
```

## CIA and The Adjustment Formula
 
## Positivity Assumption

## An Identification Example with Data

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.518818Z', start_time: '2023-06-25T15:09:31.507110Z'}
df = pd.DataFrame(dict(
    profits_prev_6m=[1.0, 1.0, 1.0, 5.0, 5.0, 5.0],
    consultancy=[0, 0, 1, 0, 1, 1],
    profits_next_6m=[1, 1.1, 1.2, 5.5, 5.7, 5.7],
))

df
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.528085Z', start_time: '2023-06-25T15:09:31.520733Z'}
(df.query("consultancy==1")["profits_next_6m"].mean() 
 - df.query("consultancy==0")["profits_next_6m"].mean())
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.538760Z', start_time: '2023-06-25T15:09:31.529677Z'}
avg_df = (df
          .groupby(["consultancy", "profits_prev_6m"])
          ["profits_next_6m"]
          .mean())

avg_df.loc[1] - avg_df.loc[0] 
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.745712Z', start_time: '2023-06-25T15:09:31.540150Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir":"LR"})
g.edge("U", "T")
g.edge("U", "Y")
g.edge("T", "M")
g.edge("M", "Y")

g
```

## Confounding Bias
 
The first significant cause of bias is confounding. It's the bias we've been discussing so far. Now, we are just putting a name to it. **Confounding happens when there is an open backdoor path through which association flows non-causally, usually because the treatment and the outcome share a common cause**. For example, let's say that you work in HR and you want to know if your new management training program is increasing employers' engagement. However, since the training is optional, you believe only managers that are already doing great attend the program and those who need it the most, don't. When you measure engagement of the teams under the managers that took the training, it is much higher than that of the teams under the managers who didn't attend the training. But it's hard to know how much of this is causal. Since there is a common cause between treatment and outcome (the training and being a good manager, respectively) they would move together regardless of a causal effect. 
 
To identify that causal effect, you need to close all backdoor paths between the treatment and the outcome. If you do so, the only effect that will be left is the direct effect $T \to Y$. In our example, you could somehow control for the manager's quality prior to taking the training. In that situation, the difference in the outcome will be only due to the training, since manager quality prior to the training would be held constant between treatment and control. Simply put, **to adjust for confounding bias, you need to adjust for the common causes of the treatment and the outcome**.

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:31.958504Z', start_time: '2023-06-25T15:09:31.756409Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir":"LR"})
g.edge("X", "T")
g.edge("X", "Y")
g.edge("T", "Y")

g.edge("Manager Quality", "Training"),
g.edge("Manager Quality", "Engagement"),
g.edge("Training", "Engagement")

g
```


### Surrogate Confounding

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.157902Z', start_time: '2023-06-25T15:09:31.960159Z'}
#| tags: [hide-input]
g = gr.Digraph()
g.edge("X1", "U")
g.edge("U", "X2")
g.edge("U", "T")
g.edge("T", "Y")
g.edge("U", "Y")

g.edge("Manager Quality", "Team's Attrition")
g.edge("Manager Quality", "Team's Past Performance")
g.edge("Manager's Tenure", "Manager Quality")
g.edge("Manager's Education Level", "Manager Quality")

g.edge("Manager Quality", "Training")
g.edge("Training", "Engagement")
g.edge("Manager Quality", "Engagement")

g
```

### Randomization Revisited

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.361584Z', start_time: '2023-06-25T15:09:32.160291Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir":"LR"})
g.edge("rnd", "T")
g.edge("T", "Y")
g.edge("U", "Y")

g
```

## Selection Bias
 
### Conditioning on a Collider

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.574282Z', start_time: '2023-06-25T15:09:32.363619Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir": "LR"})
g.edge("T", "S")
g.edge("T", "Y")
g.edge("Y", "S")
g.node("S", color="lightgrey", style="filled")

g.edge("RND", "New Feature"),
g.edge("New Feature", "Customer Satisfaction"),
g.edge("Customer Satisfaction", "NPS"),
g.edge("Customer Satisfaction", "Response"),
g.edge("New Feature", "Response"),
g.node("Response", "Response", color="lightgrey", style="filled")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.581278Z', start_time: '2023-06-25T15:09:32.576515Z'}
nps_model = nx.DiGraph([
   ("RND", "New Feature"),
#     ("New Feature", "Customer Satisfaction"),
    ("Customer Satisfaction", "NPS"),
    ("Customer Satisfaction", "Response"),
    ("New Feature", "Response"),
])


not(nx.d_separated(nps_model, {"NPS"}, {"New Feature"}, {"Response"}))
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.622363Z', start_time: '2023-06-25T15:09:32.582667Z'}
#| scrolled: true
#| tags: [hide-input]
np.random.seed(2)
n = 100000
new_feature = np.random.binomial(1, 0.5, n)

satisfaction_0 = np.random.normal(0, 0.5, n)
satisfaction_1 = satisfaction_0 + 0.4
satisfaction = new_feature*satisfaction_1 + (1-new_feature)*satisfaction_0

nps_0 = np.random.normal(satisfaction_0, 1)
nps_1 = np.random.normal(satisfaction_1, 1)
nps = new_feature*nps_1 + (1-new_feature)*nps_0


responded  = (np.random.normal(0 + new_feature + satisfaction, 1) > 1).astype(int)

tr_df = pd.DataFrame(dict(new_feature=new_feature,
                          responded=responded,
                          nps_0=nps_0,
                          nps_1=nps_1,
                          nps=nps))

tr_df_measurable = pd.DataFrame(dict(new_feature=new_feature,
                                     responded=responded,
                                     nps_0=np.nan,
                                     nps_1=np.nan,
                                     nps=np.where(responded, nps, np.nan)))

tr_df.groupby("new_feature").mean()
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.634960Z', start_time: '2023-06-25T15:09:32.624532Z'}
#| tags: [hide-input]
tr_df_measurable.groupby("new_feature").mean().assign(**{"nps": np.nan})
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.647398Z', start_time: '2023-06-25T15:09:32.636260Z'}
#| tags: [hide-input]
tr_df_measurable.groupby(["responded", "new_feature"]).mean()
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.658749Z', start_time: '2023-06-25T15:09:32.648693Z'}
#| tags: [hide-input]
tr_df.groupby(["responded", "new_feature"]).mean()
```

### Adjusting for Selection Bias

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:32.862849Z', start_time: '2023-06-25T15:09:32.660473Z'}
#| tags: [hide-input]
g = gr.Digraph()

g.edge("U", "X")
g.edge("X", "S")
g.edge("U", "Y")
g.edge("T", "Y")
g.edge("T", "S")
g.node("S", color="lightgrey", style="filled")

g.edge("New Feature", "Customer Satisfaction"),
g.edge("Unknown Stuff", "Customer Satisfaction"),
g.edge("Unknown Stuff", "Time in App"),
g.edge("Time in App", "Response"),
g.edge("New Feature", "Response"),

g.node("Response", "Response", color="lightgrey", style="filled")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:33.077565Z', start_time: '2023-06-25T15:09:32.864909Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir": "LR"})

g.edge("X1", "U")
g.edge("U", "X2")
g.edge("X5", "S")
g.edge("U", "Y",style="dashed")
g.edge("U", "S",style="dashed")
g.edge("U", "X3")
g.edge("X3", "S")
g.edge("Y", "X4")
g.edge("X4", "S")
g.edge("T", "X5")
g.edge("T", "Y")
g.edge("T", "S", style="dashed")
g.node("S", color="lightgrey", style="filled")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:33.083084Z', start_time: '2023-06-25T15:09:33.079557Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir":"LR"})

g.edge("Y", "X")
g.edge("T", "X")
g.edge("T", "Y")

g;
```

### Conditioning on a Mediator

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:33.283592Z', start_time: '2023-06-25T15:09:33.084471Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir": "LR"})
g.edge("T", "M")
g.edge("T", "Y")
g.edge("M", "Y")
g.node("M", color="lightgrey", style="filled")

g.edge("woman", "seniority")
g.edge("woman", "salary")
g.edge("seniority", "salary")
g.node("seniority", color="lightgrey", style="filled")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:33.488061Z', start_time: '2023-06-25T15:09:33.285736Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir": "LR"})
g.edge("T", "M")
g.edge("T", "Y")
g.edge("M", "Y")
g.edge("M", "X")
g.node("X", color="lightgrey", style="filled")

g
```

## Key Ideas

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:33.691694Z', start_time: '2023-06-25T15:09:33.489722Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir":"LR", "ratio": "0.3"})
g.edge("U", "T")
g.edge("U", "Y")
g.edge("T", "Y")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:33.906872Z', start_time: '2023-06-25T15:09:33.693870Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir":"LR"})
g.edge("T", "M")
g.edge("M", "Y")
g.edge("T", "Y")
g.edge("T", "S")
g.edge("Y", "S")

g.node("M", color="lightgrey", style="filled")
g.node("S", color="lightgrey", style="filled")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:34.134806Z', start_time: '2023-06-25T15:09:33.909096Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir":"LR"})
g.edge("T", "In-Game Purchase")
g.edge("T", "In-Game Purchase > 0")
g.edge("In-Game Purchase", "In-Game Purchase > 0")

g.node("In-Game Purchase > 0", color="lightgrey", style="filled")

g
```

```{python}
#| ExecuteTime: {end_time: '2023-06-25T15:09:34.357947Z', start_time: '2023-06-25T15:09:34.136697Z'}
#| tags: [hide-input]
g = gr.Digraph(graph_attr={"rankdir": "LR"})
g.edge("loan amount", "Default at yr=1")
g.edge("Default at yr=1", "Default at yr=2")
g.edge("Default at yr=2", "Default at yr=3")
g.edge("U", "Default at yr=1")
g.edge("U", "Default at yr=2")
g.edge("U", "Default at yr=3")

g.node("Default at yr=1", color="lightgrey", style="filled")
g.node("Default at yr=2", color="darkgrey", style="filled")

g
```


